### 결제하기
POST http://localhost:8080/payment
Content-Type: application/json

{
  "reservationId": 1
}

## 응답

{
  "message": "요청에 성공하였습니다.",
  "data": {
    "id": 1,
    "amount": 2000,
    "date": "2025-01-03T08:56:48.8059236"
  },
  "success": true
}

